### PR TITLE
Fixes #116:

### LINKED ISSUE #84: Null Fastval should not output as 0 when used as numeric values
Right now a `NullValue` `Fastval` outputs to `0` or `0.0` when its `AsUint()/AsInt()/AsFloat64()` is called.
Since 0 is commonly used as values, it could easily lead to an incorrect match. Consider the following test case that incorrectly matches:

```
	fe = &FilterExpression{}
	err = parser.ParseString("fieldpath.path IS NOT NULL", fe)
...
	userData := map[string]interface{}{
		"fieldpath": map[string]interface{}{
			"path": 0,
		},
	}
	udMarsh, _ := json.Marshal(userData)
	match, err := m.Match(udMarsh)
...
```

`fieldpath.path` is not null in this case but because the nil value on the right side of `EqualsExpr` inserted by the parser equates to 0 when matches with LHS's 0(int), this evaluation results in the incorrect value.

The simplest way to do it IMO is to make `NullValue` output `MinInt64/MaxUint64/MaxFloat64` when `AsInt()/AsUint()/AsFloat()` is called. Chances are, those values are unlikely to exist in real world scenarios.

Another option is to do more complicated checks in `CompareOp`, which is more correct, but that will break the pretty symmetric function of the current code.

Thoughts, @brett19 ?

### LINKED ISSUE #116: reword error for "runtime error: index out of range"
When a weird filter gets entered, like:
(int>equals10000) AND (int<>1000000) OR (float IS NOT NULL)

gojsonsm will be looking for "equals10000" in the doc. If it's not found, it returns an error "runtime error: index out of range"

It'd be nice to check for this condition and return something prettier as this message may cause mass hysteria when customers or support sees it.

### PR DESCRIPTION
**Pull request by nelio2k**
- Ensure that afterNodes matchOp will realize if certain slots are actually valid or not.
  If the slots are not valid, then don't run the actual matchOp, which is what the non
  after's case is supposed to be
- Also fixed a bug where after's matchOp wasn't pulling out an object fastval correctly
  as the implementation was not there
- Fix matcher Reset() where it wipes out old slots
- Added new test data

### CODE REVIEW

**Comment by nelio2k** [comment]
The example is given the comparison
int > equals10000 
where equals10000 is missing.

Without the valid comparison, what happens is that equals10000 becomes 0 and the statement becomes true if int is >0.
The same statement becomes false if int < 0.
So the behavior is a bit odd.

Then there's also addressing the original issue of https://github.com/couchbaselabs/gojsonsm/issues/84
which is pretty much almost the same thing.

**Comment by brett19** [comment]
Hey @nelio2k,
Based on your description of the issue, it sounds like there is actually a more fundamental failure occurring here, maybe two.  It sounds like `equals10000` is being parsed as an identifier referring to the document content, then you end up with a query that is `SOMETHING > `$doc`.\`equals1000\`.   So that would mean that for one, this is being incorrectly executed when it should not be, since you would expect a document to contain a field called `equals1000`.  Secondly, it seems like there needs to be some sort of NaN or Nil value handling such that the comparisons make sense when the values cannot be parsed as expected, there are a lot of well-written rules out there on how to handle these cases once they are separated out.

After writing that, I think the problem is the use of variables and the fact that those comparisons get placed into an :AFTER block since they have variables on the left and right side.  It's possible that variables need to be checked for values before they are used.

**Comment by nelio2k** [comment]
@brett19 You were right in your assessment.
I've re-addressed this and addressed some other things along the way. 
Please take a look. Thanks.

File: fastMatcher.go [hunk 1]
```diff
@@ -11,23 +11,29 @@ type slotData struct {
...
+var emptySlotData slotData
+
 type FastMatcher struct {
-	def     MatchDef
-	slots   []slotData
-	buckets *binTreeState
-	tokens  jsonTokenizer
+	def      MatchDef
+	slots    []slotData
+	numSlots int
```
Comment (brett19) [inline fastMatcher.go]: Why copy numSlots into the matcher?  Why not simply use `matcher.def.numSlots`?

File: fastMatcher.go [hunk 2]
```diff
@@ -222,20 +234,37 @@ func (m *FastMatcher) matchOp(op *OpNode, litVal *FastVal) error {
...
 	if op.Rhs != nil {
 		rhsVal = m.resolveParam(op.Rhs, litVal)
+		if _, ok := op.Rhs.(SlotRef); ok && rhsVal.IsMissing() {
+			slotNotFound = true
+		}
 	} else if litVal != nil {
 		rhsVal = *litVal
 	}
 
+	if slotNotFound {
```
Comment (brett19) [inline fastMatcher.go]: For performance reasons, the match tree is designed to not require you to explicitly mark something as false, although marking it as false also gives more opportunities to early-out.  Did you investigate which one provided more benefit?

File: fastMatcher.go [hunk 3]
```diff
@@ -548,7 +577,7 @@ func (m *FastMatcher) matchExec(token tokenType, tokenData []byte, tokenDataLen
 			}
 		}
 	} else if token == tknObjectStart {
-		objStartPos := m.tokens.Position()
+		objStartPos := m.tokens.Position() - 1 /* to include the objStart itself*/
```
Comment (brett19) [inline fastMatcher.go]: This does not seem related to the slots changes.  What is this?

File: fastMatcher.go (hunk 1 above)
Comment (nelio2k) [reply fastMatcher.go]: True. Done

File: fastMatcher.go (hunk 2 above)
Comment (nelio2k) [reply fastMatcher.go]: I just tried, and either case the perf is pretty much the same... prob because we're really talking about the after block

File: fastMatcher.go (hunk 3 above)
Comment (nelio2k) [reply fastMatcher.go]: Just something that when I was doing testing I found the obj FastVal was w/o the "{"
Since this PR also addresses the issue of doing object comparison, I took the liberty and fixed that here.

File: fastMatcher.go (hunk 2 above)
Comment (nelio2k) [reply fastMatcher.go]: I do realize I'm missing a return statement in this if block
