### PR TITLE
Fixes #99 - int comparison to a large float that overflows an int64 s…

### LINKED ISSUE #99: fastLitParser should parse number into float64 if int64 overflows
When an integer fastVal is used to compare against a float, and the float that is being compared to can overflow an int64, the comparison result is more than likely to be incorrect.

### PR DESCRIPTION
**Pull request by nelio2k**
…hould use float comparison

It's possible that we lose some precision w.r.t to the integer when we convert it to a float, but it's potentially less problematic than having a overflow that causes signs to flip, leading to egregious results.

### CODE REVIEW

File: fastval.go [hunk 1]
```diff
@@ -302,9 +302,27 @@ func (val FastVal) ToJsonString() (FastVal, error) {
 	return val, errors.New("invalid type coercion")
 }
 
+func (val FastVal) floatToIntOverflows() bool {
+	intVal := val.AsInt()
+	floatVal := val.GetFloat()
+
+	if floatVal >= 0 && intVal < 0 {
```
Comment (ysui6888) [inline fastval.go]: not sure whether these checks are sufficient. In float to integer conversion, when the integral part does not fit in int64, the end behavior is said to be implementation dependent. I don't think we can assume that the sign will always change.

File: filterExprParser_test.go [hunk 2]
```diff
@@ -206,7 +206,7 @@ func TestFilterExpressionParser(t *testing.T) {
 	userData = map[string]interface{}{
 		"onePath": map[string]interface{}{
 			"field1": -2,
-			"field2": 2,
+			"field2": 2e30,
 		},
```
Comment (ysui6888) [inline filterExprParser_test.go]: i don't think this will overflow int64. 2e60 could.

Comment (nelio2k) [reply filterExprParser_test.go]: Largest int64 is 9223372036854775808
2e20 could overflow it.

File: fastval.go (hunk 1 above)
Comment (nelio2k) [reply fastval.go]: OK that's fair. I'll look at another way.

File: filterExprParser_test.go (hunk 2 above)
Comment (ysui6888) [reply filterExprParser_test.go]: 2e30 is 2*e^30, correct? int64 can hold 2^63 even without the sign bit.  e<4, so e30 < 2^61

Comment (nelio2k) [reply filterExprParser_test.go]: The e is scientific notation and not the euler's number (I think that's what you mean?)
https://stackoverflow.com/questions/13617818/json-e-and-json-e

File: fastval.go (hunk 1 above)
Comment (nelio2k) [reply fastval.go]: There are some concerns with comparisons using math constants (in C/C++ at least). The recommendation was to use the above method.
https://stackoverflow.com/questions/526070/handling-overflow-when-casting-doubles-to-integers-in-c

Golang may be a little different but the recommended method should be safe regardless.

File: fastval.go [hunk 3]
```diff
@@ -302,9 +302,26 @@ func (val FastVal) ToJsonString() (FastVal, error) {
 	return val, errors.New("invalid type coercion")
 }
 
+func (val FastVal) floatToIntOverflows() bool {
+	floatVal := val.GetFloat()
+
+	// Instead of using math constants that could potentially lead to rounding errors,
+	// force a float-to-float comparison here
+	if !(floatVal >= -9223372036854775808.0 && floatVal < 9223372036854775808.0) {
```
Comment (ysui6888) [inline fastval.go]: better to use MaxInt64 and MinInt64

File: fastval.go [hunk 4]
```diff
@@ -302,9 +302,26 @@ func (val FastVal) ToJsonString() (FastVal, error) {
...
+	}
+}
+
 func (val FastVal) compareInt(other FastVal) int {
 	intVal := val.AsInt()
 	intOval := other.AsInt()
+
+	if other.dataType == FloatValue && other.floatToIntOverflows() {
+		return val.compareFloat(other)
+	}
```
Comment (ysui6888) [inline fastval.go]: move this to beginning of method

File: fastval.go (hunk 3 above)
Comment (nelio2k) [reply fastval.go]: I suppose the rounding error probability is miniscule.

Comment (ysui6888) [reply fastval.go]: you could do float(MaxInt64) before you compare.

Comment (nelio2k) [reply fastval.go]: It's probably not needed

Comment (ysui6888) [reply fastval.go]: how do we verify "92233.." is the right number to use, then? will the test data be based on MaxInt64?

Comment (nelio2k) [reply fastval.go]: I changed the latest changeset to MaxInt64 and MinInt64

File: fastval.go (hunk 4 above)
Comment (nelio2k) [reply fastval.go]: done

File: fastval.go [hunk 5]
```diff
@@ -302,9 +302,26 @@ func (val FastVal) ToJsonString() (FastVal, error) {
 	return val, errors.New("invalid type coercion")
 }
 
+func (val FastVal) floatToIntOverflows() bool {
+	floatVal := val.GetFloat()
+
+	// Instead of using math constants that could potentially lead to rounding errors,
+	// force a float-to-float comparison here
+	if !(floatVal >= math.MinInt64 && floatVal < math.MaxInt64) {
```
Comment (ysui6888) [inline fastval.go]: <=?

Comment (nelio2k) [reply fastval.go]: Yes, that's true now using MaxInt64
