### PR TITLE
Fixes #77: Fix bug where After was not being executed

### LINKED ISSUE #77: Matcher does not execute the Afters in the top root node
When the top level ExecNode contains Afters and does not get run, it could lead to incorrect results.

For example, something simple like:
`field0 < field1`

would not be executed and the result would be incorrect.

### PR DESCRIPTION
**Pull request by nelio2k**
While writing EBNF parser and testing results, found out issue #77 ... the unit test is not here but will be in another commit that goes alongside the new parser.

### CODE REVIEW

File: matcher.go [hunk 1]
```diff
@@ -714,6 +718,11 @@ func (m *Matcher) Match(data []byte) (bool, error) {
 		return false, err
 	}
 
+	// It is possible that the root execNode has Afters that have not been executed yet
```
Comment (nelio2k) [inline matcher.go]: I thought I removed it. Hang on
